kind: Deployment
apiVersion: apps/v1
metadata:
  name: precision-map
  namespace: default
  labels:
    app: precision-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: precision-map
  template:
    metadata:
      name: precision-map
      labels:
        app: precision-map
    spec:
      containers:
        - name: precision-map
          image: bawenna/precision-map:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: precision-map
spec:
  type: NodePort
  selector:
    app: precision-map
  ports:
    - port: 5000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: precision-map-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: precision-map
          servicePort: 5000
---